### ISSUE TITLE
sy-ucomm

### ISSUE THREAD

**Issue by larshp** [abapkochbuch/Sources#4]
Hi,
Does the statement 

`DATA:      sy-ucomm LIKE sy-ucomm.`

do anything? Is it needed?

https://github.com/abapkochbuch/Sources/blob/master/kapitel_04/mzbook_demotop.prog.abap#L22

**Comment by tricktresor** [comment]
ui. That's weird... :]
The data definition is useless. 
I deleted it.
Thanks!
Enno
